In [50]:
import pandas as pd
from zipfile import ZipFile
import numpy as np
from datetime import datetime, timedelta,date
from urllib.request import urlopen
from io import BytesIO

In [39]:
sec_base_url='https://archives.nseindia.com/products/content'
fno_base_url='https://archives.nseindia.com/content/historical/DERIVATIVES'

In [36]:
startdate=date(2021,11,18)
sec_date=startdate.strftime('%d%m%Y')
fno_day=startdate.strftime("%d")
fno_month=startdate.strftime("%b").upper()
fno_year=startdate.strftime("%Y")
fno_date=startdate.strftime('%d%b%Y').upper()

In [38]:
print(startdate,sec_date,fno_month,fno_year,fno_date)

2021-11-18 18112021 NOV 2021 18NOV2021

In [44]:
sec_url=f"{sec_base_url}/sec_bhavdata_full_{sec_date}.csv"
fno_url=f"{fno_base_url}/{fno_year}/{fno_month}/fo{fno_date}bhav.csv.zip"
fno_csv_file_name=f"fo{fno_date}bhav.csv"

In [ ]:
#https://archives.nseindia.com/products/content/sec_bhavdata_full_01102019.csv
#https://archives.nseindia.com/content/historical/DERIVATIVES/2019/OCT/fo01OCT2019bhav.csv.zip

In [56]:
#this is how to download csv zip then unzip it and then load to pandas

resp = urlopen(fno_url)
zipfile = ZipFile(BytesIO(resp.read()))
myfile=zipfile.extractall()
df=pd.read_csv(fno_csv_file_name)
df

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,25-Nov-2021,0.0,XX,38102.35,38314.90,37821.30,38105.70,38105.70,140666,1337791.99,2022300,10650,18-NOV-2021,NaN
1,FUTIDX,BANKNIFTY,30-Dec-2021,0.0,XX,38294.15,38473.95,38000.05,38253.70,38253.70,21520,205492.20,493150,96875,18-NOV-2021,NaN
2,FUTIDX,BANKNIFTY,27-Jan-2022,0.0,XX,38450.00,38627.10,38150.00,38412.05,38412.05,1748,16752.44,35825,3150,18-NOV-2021,NaN
3,FUTIDX,FINNIFTY,23-Nov-2021,0.0,XX,18700.00,18700.00,17720.00,18580.00,18580.00,19,140.52,440,120,18-NOV-2021,NaN
4,FUTIDX,FINNIFTY,30-Nov-2021,0.0,XX,18730.05,18730.05,18435.55,18435.55,18628.90,7,52.25,1160,0,18-NOV-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68300,OPTSTK,ZEEL,27-Jan-2022,365.0,PE,0.00,0.00,0.00,90.65,74.35,0,0.00,0,0,18-NOV-2021,NaN
68301,OPTSTK,ZEEL,27-Jan-2022,370.0,PE,0.00,0.00,0.00,94.40,77.95,0,0.00,0,0,18-NOV-2021,NaN
68302,OPTSTK,ZEEL,27-Jan-2022,375.0,PE,0.00,0.00,0.00,98.20,81.65,0,0.00,0,0,18-NOV-2021,NaN
68303,OPTSTK,ZEEL,27-Jan-2022,380.0,PE,0.00,0.00,0.00,102.05,85.40,0,0.00,0,0,18-NOV-2021,NaN
68304,OPTSTK,ZEEL,27-Jan-2022,385.0,PE,0.00,0.00,0.00,106.00,89.25,0,0.00,0,0,18-NOV-2021,NaN

In [13]:
date.strftime("%b").upper()

'NOV'

In [24]:
start='2019-10-01'
end='2021-11-18'
daterange=np.arange(np.datetime64(start), np.datetime64(end)).astype(datetime)
print(daterange[0].strftime('%d%m%Y'))
day=daterange[0].strftime("%d")
month=daterange[0].strftime("%m")
year=daterange[0].strftime("%Y")
mmm=daterange[0].strftime("%b").upper()

print(day,month,year,mmm)

#date_list = [(start_date + datetime.timedelta(days = day)).isoformat() for day in range(number_of_days)]

01102019
01 10 2019 OCT